# Generated by Django 4.1.5 on 2023-01-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_tag_image_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
