# Generated by Django 4.1.5 on 2023-01-14 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0005_image_file_mtime"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="import_time",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
