# Generated by Django 4.1.5 on 2025-10-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0006_image_import_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="reviewed",
            field=models.BooleanField(default=False),
        ),
    ]
