# Generated by Django 4.1.5 on 2026-06-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0007_image_reviewed"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="phash",
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="sha256",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
