# Generated by Django 4.1.5 on 2026-06-20 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0008_image_phash_image_sha256"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merged_from",
                to="images.image",
            ),
        ),
    ]
