# Generated by Django 4.1.5 on 2026-06-20 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0009_image_merged_into"),
    ]

    operations = [
        migrations.CreateModel(
            name="DismissedDuplicate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="images.image",
                    ),
                ),
                (
                    "image_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="images.image",
                    ),
                ),
            ],
            options={
                "unique_together": {("image_a", "image_b")},
            },
        ),
    ]
